
create table stock (
       ts_code char(9) not null,
       symbol char(6) not null,
       name varchar(10),
       area varchar(5),
       industry varchar(5),
       fullname varchar(50),
       enname varchar(100),
       market varchar(5),
       exchange varchar(5),
       curr_type char(3),
       list_status char(1),
       list_date date,
       delist_date date,
       is_hs char(1),
       chairman varchar(30),
       manager varchar(30),
       secretary varchar(30),
       reg_capital decimal(15,4),
       setup_date date,
       province varchar(5),
       city varchar(20),
       introduction varchar(1000),
       website varchar(50),
       email varchar(200),
       office varchar(100),
       employees int,
       main_business varchar(500),
       business_scope varchar(2000),
       primary key(ts_code),
       key(symbol)
       ) engine = InnoDB default charset = utf8;

