
create table stock_daily_0 (
       ts_code char(9) not null,
       trade_date date not null,
       open decimal(6,2),
       high decimal(6,2),
       low decimal(6,2),
       close decimal(6,2),
       pre_close decimal(6,2),
       chg decimal(6,2),
       pct_chg decimal(8,4),
       vol decimal(10,2),
       amount decimal(11,3),
       adj_factor decimal(8,3),
       turnover_rate decimal(8,4),
       turnover_rate_f decimal(8,4),
       volume_ratio decimal(6,2),
       pe decimal(10,4),
       pe_ttm decimal(10,4),
       pb decimal(10,4),
       ps decimal(10,4),
       ps_ttm decimal(10,4),
       dv_ratio decimal(6,4),
       dv_ttm decimal(6,4),
       total_share decimal(13,4),
       float_share decimal(13,4),
       free_share decimal(13,4),
       total_mv decimal(14,4),
       circ_mv decimal(14,4),
       primary key(ts_code, trade_date)
       ) engine = InnoDB default charset = utf8;

create table stock_daily_1 (
       ts_code char(9) not null,
       trade_date date not null,
       open decimal(6,2),
       high decimal(6,2),
       low decimal(6,2),
       close decimal(6,2),
       pre_close decimal(6,2),
       chg decimal(6,2),
       pct_chg decimal(8,4),
       vol decimal(10,2),
       amount decimal(11,3),
       adj_factor decimal(8,3),
       turnover_rate decimal(8,4),
       turnover_rate_f decimal(8,4),
       volume_ratio decimal(6,2),
       pe decimal(10,4),
       pe_ttm decimal(10,4),
       pb decimal(10,4),
       ps decimal(10,4),
       ps_ttm decimal(10,4),
       dv_ratio decimal(6,4),
       dv_ttm decimal(6,4),
       total_share decimal(13,4),
       float_share decimal(13,4),
       free_share decimal(13,4),
       total_mv decimal(14,4),
       circ_mv decimal(14,4),
       primary key(ts_code, trade_date)
       ) engine = InnoDB default charset = utf8;

create table stock_daily_2 (
       ts_code char(9) not null,
       trade_date date not null,
       open decimal(6,2),
       high decimal(6,2),
       low decimal(6,2),
       close decimal(6,2),
       pre_close decimal(6,2),
       chg decimal(6,2),
       pct_chg decimal(8,4),
       vol decimal(10,2),
       amount decimal(11,3),
       adj_factor decimal(8,3),
       turnover_rate decimal(8,4),
       turnover_rate_f decimal(8,4),
       volume_ratio decimal(6,2),
       pe decimal(10,4),
       pe_ttm decimal(10,4),
       pb decimal(10,4),
       ps decimal(10,4),
       ps_ttm decimal(10,4),
       dv_ratio decimal(6,4),
       dv_ttm decimal(6,4),
       total_share decimal(13,4),
       float_share decimal(13,4),
       free_share decimal(13,4),
       total_mv decimal(14,4),
       circ_mv decimal(14,4),
       primary key(ts_code, trade_date)
       ) engine = InnoDB default charset = utf8;

create table stock_daily_3 (
       ts_code char(9) not null,
       trade_date date not null,
       open decimal(6,2),
       high decimal(6,2),
       low decimal(6,2),
       close decimal(6,2),
       pre_close decimal(6,2),
       chg decimal(6,2),
       pct_chg decimal(8,4),
       vol decimal(10,2),
       amount decimal(11,3),
       adj_factor decimal(8,3),
       turnover_rate decimal(8,4),
       turnover_rate_f decimal(8,4),
       volume_ratio decimal(6,2),
       pe decimal(10,4),
       pe_ttm decimal(10,4),
       pb decimal(10,4),
       ps decimal(10,4),
       ps_ttm decimal(10,4),
       dv_ratio decimal(6,4),
       dv_ttm decimal(6,4),
       total_share decimal(13,4),
       float_share decimal(13,4),
       free_share decimal(13,4),
       total_mv decimal(14,4),
       circ_mv decimal(14,4),
       primary key(ts_code, trade_date)
       ) engine = InnoDB default charset = utf8;

create table stock_daily_4 (
       ts_code char(9) not null,
       trade_date date not null,
       open decimal(6,2),
       high decimal(6,2),
       low decimal(6,2),
       close decimal(6,2),
       pre_close decimal(6,2),
       chg decimal(6,2),
       pct_chg decimal(8,4),
       vol decimal(10,2),
       amount decimal(11,3),
       adj_factor decimal(8,3),
       turnover_rate decimal(8,4),
       turnover_rate_f decimal(8,4),
       volume_ratio decimal(6,2),
       pe decimal(10,4),
       pe_ttm decimal(10,4),
       pb decimal(10,4),
       ps decimal(10,4),
       ps_ttm decimal(10,4),
       dv_ratio decimal(6,4),
       dv_ttm decimal(6,4),
       total_share decimal(13,4),
       float_share decimal(13,4),
       free_share decimal(13,4),
       total_mv decimal(14,4),
       circ_mv decimal(14,4),
       primary key(ts_code, trade_date)
       ) engine = InnoDB default charset = utf8;

create table stock_daily_5 (
       ts_code char(9) not null,
       trade_date date not null,
       open decimal(6,2),
       high decimal(6,2),
       low decimal(6,2),
       close decimal(6,2),
       pre_close decimal(6,2),
       chg decimal(6,2),
       pct_chg decimal(8,4),
       vol decimal(10,2),
       amount decimal(11,3),
       adj_factor decimal(8,3),
       turnover_rate decimal(8,4),
       turnover_rate_f decimal(8,4),
       volume_ratio decimal(6,2),
       pe decimal(10,4),
       pe_ttm decimal(10,4),
       pb decimal(10,4),
       ps decimal(10,4),
       ps_ttm decimal(10,4),
       dv_ratio decimal(6,4),
       dv_ttm decimal(6,4),
       total_share decimal(13,4),
       float_share decimal(13,4),
       free_share decimal(13,4),
       total_mv decimal(14,4),
       circ_mv decimal(14,4),
       primary key(ts_code, trade_date)
       ) engine = InnoDB default charset = utf8;

create table stock_daily_6 (
       ts_code char(9) not null,
       trade_date date not null,
       open decimal(6,2),
       high decimal(6,2),
       low decimal(6,2),
       close decimal(6,2),
       pre_close decimal(6,2),
       chg decimal(6,2),
       pct_chg decimal(8,4),
       vol decimal(10,2),
       amount decimal(11,3),
       adj_factor decimal(8,3),
       turnover_rate decimal(8,4),
       turnover_rate_f decimal(8,4),
       volume_ratio decimal(6,2),
       pe decimal(10,4),
       pe_ttm decimal(10,4),
       pb decimal(10,4),
       ps decimal(10,4),
       ps_ttm decimal(10,4),
       dv_ratio decimal(6,4),
       dv_ttm decimal(6,4),
       total_share decimal(13,4),
       float_share decimal(13,4),
       free_share decimal(13,4),
       total_mv decimal(14,4),
       circ_mv decimal(14,4),
       primary key(ts_code, trade_date)
       ) engine = InnoDB default charset = utf8;

create table stock_daily_7 (
       ts_code char(9) not null,
       trade_date date not null,
       open decimal(6,2),
       high decimal(6,2),
       low decimal(6,2),
       close decimal(6,2),
       pre_close decimal(6,2),
       chg decimal(6,2),
       pct_chg decimal(8,4),
       vol decimal(10,2),
       amount decimal(11,3),
       adj_factor decimal(8,3),
       turnover_rate decimal(8,4),
       turnover_rate_f decimal(8,4),
       volume_ratio decimal(6,2),
       pe decimal(10,4),
       pe_ttm decimal(10,4),
       pb decimal(10,4),
       ps decimal(10,4),
       ps_ttm decimal(10,4),
       dv_ratio decimal(6,4),
       dv_ttm decimal(6,4),
       total_share decimal(13,4),
       float_share decimal(13,4),
       free_share decimal(13,4),
       total_mv decimal(14,4),
       circ_mv decimal(14,4),
       primary key(ts_code, trade_date)
       ) engine = InnoDB default charset = utf8;

create table stock_daily_8 (
       ts_code char(9) not null,
       trade_date date not null,
       open decimal(6,2),
       high decimal(6,2),
       low decimal(6,2),
       close decimal(6,2),
       pre_close decimal(6,2),
       chg decimal(6,2),
       pct_chg decimal(8,4),
       vol decimal(10,2),
       amount decimal(11,3),
       adj_factor decimal(8,3),
       turnover_rate decimal(8,4),
       turnover_rate_f decimal(8,4),
       volume_ratio decimal(6,2),
       pe decimal(10,4),
       pe_ttm decimal(10,4),
       pb decimal(10,4),
       ps decimal(10,4),
       ps_ttm decimal(10,4),
       dv_ratio decimal(6,4),
       dv_ttm decimal(6,4),
       total_share decimal(13,4),
       float_share decimal(13,4),
       free_share decimal(13,4),
       total_mv decimal(14,4),
       circ_mv decimal(14,4),
       primary key(ts_code, trade_date)
       ) engine = InnoDB default charset = utf8;

create table stock_daily_9 (
       ts_code char(9) not null,
       trade_date date not null,
       open decimal(6,2),
       high decimal(6,2),
       low decimal(6,2),
       close decimal(6,2),
       pre_close decimal(6,2),
       chg decimal(6,2),
       pct_chg decimal(8,4),
       vol decimal(10,2),
       amount decimal(11,3),
       adj_factor decimal(8,3),
       turnover_rate decimal(8,4),
       turnover_rate_f decimal(8,4),
       volume_ratio decimal(6,2),
       pe decimal(10,4),
       pe_ttm decimal(10,4),
       pb decimal(10,4),
       ps decimal(10,4),
       ps_ttm decimal(10,4),
       dv_ratio decimal(6,4),
       dv_ttm decimal(6,4),
       total_share decimal(13,4),
       float_share decimal(13,4),
       free_share decimal(13,4),
       total_mv decimal(14,4),
       circ_mv decimal(14,4),
       primary key(ts_code, trade_date)
       ) engine = InnoDB default charset = utf8;

       
